import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const COLORS = {
  primary: [6, 182, 212],
  headerDark: [15, 23, 42],
  gray: [100, 116, 139],
  text: [30, 41, 59],
  striped: [240, 249, 255],
  white: [255, 255, 255]
};

const PAGE_MARGIN = 20;
const SECTION_SPACING = 10;

const safeString = (value, fallback = 'N/A') => {
  if (value === null || value === undefined) return fallback;
  const text = String(value).trim();
  return text.length ? text : fallback;
};

const formatDate = (value) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toLocaleDateString();
};

const dateStamp = () => {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

const sanitizeFilePart = (value) => safeString(value, 'unknown').replace(/[^a-z0-9-_]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase();

const ensurePageSpace = (doc, y, needed = 24) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - PAGE_MARGIN) {
    doc.addPage();
    return PAGE_MARGIN;
  }
  return y;
};

const drawSectionTitle = (doc, title, y) => {
  const nextY = ensurePageSpace(doc, y, 14);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.text);
  doc.text(title, PAGE_MARGIN, nextY);
  return nextY + 7;
};

const addBrandHeader = (doc, pageTitle) => {
  let y = PAGE_MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.primary);
  doc.text('HealthEase', PAGE_MARGIN, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.gray);
  y += 6;
  doc.text('AI-Powered Healthcare', PAGE_MARGIN, y);

  if (pageTitle) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.text);
    y += 8;
    doc.text(pageTitle, PAGE_MARGIN, y);
  }

  y += 6;
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.6);
  doc.line(PAGE_MARGIN, y, doc.internal.pageSize.getWidth() - PAGE_MARGIN, y);

  return y + SECTION_SPACING;
};

const addFooter = (doc) => {
  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toLocaleString();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.gray);
    doc.text(`Generated by HealthEase on ${timestamp}`, PAGE_MARGIN, pageHeight - 8);
    doc.text(`Page ${page}/${pageCount}`, pageWidth - PAGE_MARGIN, pageHeight - 8, { align: 'right' });
  }
};

const normalizeConfidence = (value) => {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return 'N/A';
  const score = numeric <= 1 ? numeric * 100 : numeric;
  return `${Math.max(0, Math.min(100, Math.round(score)))}%`;
};

const extractReminderTimes = (reminder) => {
  const times = Array.isArray(reminder?.times) ? reminder.times : [];
  if (!times.length) return 'No times set';

  const normalized = times
    .map((item) => {
      if (typeof item === 'string') return item;
      if (item && typeof item === 'object') return item.time || item.value || '';
      return '';
    })
    .filter(Boolean);

  return normalized.length ? normalized.join(', ') : 'No times set';
};

export const exportPrescriptionPDF = (prescription) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = addBrandHeader(doc);

  y = drawSectionTitle(doc, 'Patient Details', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);

  const doctor =
    prescription?.doctorName ||
    prescription?.doctor_name ||
    prescription?.doctor ||
    'Not specified';
  const prescriptionDate = prescription?.date || prescription?.prescriptionDate || prescription?.uploadDate;

  doc.text(`Doctor: ${doctor}`, PAGE_MARGIN, y);
  y += 6;
  doc.text(`Date: ${formatDate(prescriptionDate)}`, PAGE_MARGIN, y);
  y += 6;
  doc.text(`Diagnosis: ${safeString(prescription?.diagnosis, 'Not specified')}`, PAGE_MARGIN, y);

  y += SECTION_SPACING;
  y = drawSectionTitle(doc, 'Medications', y);

  const medications = Array.isArray(prescription?.medications) ? prescription.medications : [];
  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [['Medicine', 'Dosage', 'Frequency', 'Duration']],
    body: medications.length
      ? medications.map((m) => [
          m.medicineName || m.medicine_name || m.name || 'N/A',
          m.dosage || m.dose || 'N/A',
          m.frequency || m.freq || 'N/A',
          m.duration || m.days || 'N/A'
        ])
      : [['No medications found', '-', '-', '-']],
    theme: 'striped',
    styles: { font: 'helvetica', textColor: COLORS.text },
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.striped }
  });

  y = (doc.lastAutoTable?.finalY || y) + SECTION_SPACING;
  y = drawSectionTitle(doc, 'Reminder Status', y);

  const reminderEnabled = Boolean(prescription?.reminder?.enabled);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Status: ${reminderEnabled ? 'Enabled' : 'Disabled'}`, PAGE_MARGIN, y);
  y += 6;
  doc.text(`Times: ${extractReminderTimes(prescription?.reminder)}`, PAGE_MARGIN, y);

  y += SECTION_SPACING;
  y = drawSectionTitle(doc, 'OCR Details', y);

  const confidence = normalizeConfidence(
    prescription?.ocrConfidence ?? prescription?.ocr_confidence ?? prescription?.confidenceScore ?? prescription?.extractionConfidence
  );
  const ocrModeRaw = prescription?.ocrMode || prescription?.ocr_mode;
  const mode = ocrModeRaw || (prescription?.isManual ? 'Manual' : 'Real OCR');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Confidence Score: ${confidence}`, PAGE_MARGIN, y);
  y += 6;
  doc.text(`Mode: ${safeString(mode, 'Real OCR')}`, PAGE_MARGIN, y);
  y += 6;
  doc.text(`Verified: ${prescription?.isVerified ? 'Yes' : 'No'}`, PAGE_MARGIN, y);

  addFooter(doc);

  const fileDoctor = sanitizeFilePart(doctor || 'doctor');
  const fileDate = sanitizeFilePart(formatDate(prescriptionDate));
  doc.save(`prescription-${fileDoctor}-${fileDate}.pdf`);
};

const readSummary = (summary = {}) => ({
  totalPrescriptions: summary.totalPrescriptions ?? summary.total_prescriptions ?? 0,
  activeMedications: summary.activeMedications ?? summary.active_medications ?? 0,
  remindersSet: summary.remindersSet ?? summary.reminders_set ?? 0,
  lastUploadDate: summary.lastUploadDate ?? summary.last_upload ?? ''
});

export const exportAnalyticsPDF = (analyticsData) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = addBrandHeader(doc, 'Health Analytics Report');

  const summary = readSummary(analyticsData?.summary || {});

  y = drawSectionTitle(doc, 'Summary Stats', y);

  const gridRows = [
    ['Total Prescriptions', String(summary.totalPrescriptions)],
    ['Active Medications', String(summary.activeMedications)],
    ['Reminders Set', String(summary.remindersSet)],
    ['Last Upload Date', formatDate(summary.lastUploadDate)]
  ];

  const boxWidth = (doc.internal.pageSize.getWidth() - PAGE_MARGIN * 2 - 6) / 2;
  const boxHeight = 16;
  gridRows.forEach((row, index) => {
    if (index % 2 === 0 && index > 0) y += boxHeight + 4;

    const x = PAGE_MARGIN + (index % 2) * (boxWidth + 6);
    doc.setDrawColor(203, 213, 225);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, boxWidth, boxHeight, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text(row[0], x + 3, y + 5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...COLORS.text);
    doc.text(safeString(row[1], '-'), x + 3, y + 11);
  });

  y += boxHeight + SECTION_SPACING + 6;

  y = drawSectionTitle(doc, 'Top 5 Medications', y);
  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [['Medicine Name', 'Count']],
    body: (analyticsData?.topMedications || analyticsData?.top_medications || []).map((item) => [
      safeString(item?.name, 'Unknown'),
      safeString(item?.count, '0')
    ]),
    theme: 'striped',
    styles: { font: 'helvetica', textColor: COLORS.text },
    headStyles: { fillColor: COLORS.headerDark, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.striped },
    didParseCell: (hookData) => {
      if (hookData.section === 'body' && hookData.row.raw?.length === 0) {
        hookData.cell.text = ['No data available'];
      }
    }
  });

  y = (doc.lastAutoTable?.finalY || y) + SECTION_SPACING;
  y = ensurePageSpace(doc, y, 30);

  y = drawSectionTitle(doc, 'Prescription Timeline', y);
  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [['Month', 'Upload Count']],
    body: (analyticsData?.timeline || []).map((item) => [safeString(item?.month, 'N/A'), safeString(item?.count, '0')]),
    theme: 'striped',
    styles: { font: 'helvetica', textColor: COLORS.text },
    headStyles: { fillColor: COLORS.headerDark, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.striped }
  });

  y = (doc.lastAutoTable?.finalY || y) + SECTION_SPACING;
  y = ensurePageSpace(doc, y, 30);

  y = drawSectionTitle(doc, 'Medication Frequency Breakdown', y);
  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [['Frequency', 'Count']],
    body: (analyticsData?.medicationFrequency || analyticsData?.medication_frequency || []).map((item) => [
      safeString(item?.frequency, 'N/A'),
      safeString(item?.count, '0')
    ]),
    theme: 'striped',
    styles: { font: 'helvetica', textColor: COLORS.text },
    headStyles: { fillColor: COLORS.headerDark, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.striped }
  });

  y = (doc.lastAutoTable?.finalY || y) + SECTION_SPACING;
  y = ensurePageSpace(doc, y, 30);

  y = drawSectionTitle(doc, 'Recent Prescriptions', y);
  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [['Date', 'Doctor', 'Medications Count', 'Verified']],
    body: (analyticsData?.recentPrescriptions || analyticsData?.recent_prescriptions || []).map((item) => [
      formatDate(item?.date),
      safeString(item?.doctorName || item?.doctor_name, 'UNCLEAR'),
      safeString(item?.medicationCount ?? item?.medication_count, '0'),
      item?.isVerified || item?.is_verified ? 'Yes' : 'No'
    ]),
    theme: 'striped',
    styles: { font: 'helvetica', textColor: COLORS.text },
    headStyles: { fillColor: COLORS.headerDark, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.striped }
  });

  addFooter(doc);
  doc.save(`healthease-analytics-report-${dateStamp()}.pdf`);
};
